package com.jubalrife.knucklebones.v1.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The @GeneratedValue annotation is used to mark a field of a class as generated by the database.
 * The annotated field will be ignored in insert, and update statements.
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface GeneratedValue {
}
